package episode_identity

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
)

const AmbiguitySchemaVersion = "1"

type AmbiguityDecision string

const (
	AmbiguityMatch   AmbiguityDecision = "MATCH"
	AmbiguityNoMatch AmbiguityDecision = "NO_MATCH"
	AmbiguityAbstain AmbiguityDecision = "ABSTAIN"
)

// CandidateFact is the bounded, structured input exposed to an optional AI
// backend. CandidateID is generated by the caller and is the only selectable
// value; the model cannot invent a URL, filename, or episode number.
type CandidateFact struct {
	CandidateID        string   `json:"candidate_id"`
	Supplier           string   `json:"supplier"`
	Name               string   `json:"name"`
	Season             int      `json:"season,omitempty"`
	Episode            int      `json:"episode,omitempty"`
	AbsoluteEpisode    int      `json:"absolute_episode,omitempty"`
	DeterministicScore int64    `json:"deterministic_score"`
	Evidence           []string `json:"evidence,omitempty"`
}

type AmbiguityRequest struct {
	SchemaVersion string          `json:"schema_version"`
	Media         Request         `json:"media"`
	Candidates    []CandidateFact `json:"candidates"`
}

type AmbiguityResult struct {
	SchemaVersion string            `json:"schema_version"`
	Decision      AmbiguityDecision `json:"decision"`
	CandidateID   string            `json:"candidate_id,omitempty"`
	Confidence    float64           `json:"confidence"`
	Evidence      []string          `json:"evidence,omitempty"`
	Model         string            `json:"model,omitempty"`
	ModelVersion  string            `json:"model_version,omitempty"`
}

type AmbiguityResolver interface {
	ResolveAmbiguity(ctx context.Context, request AmbiguityRequest) (AmbiguityResult, error)
}

type AmbiguityResolverFunc func(context.Context, AmbiguityRequest) (AmbiguityResult, error)

func (f AmbiguityResolverFunc) ResolveAmbiguity(ctx context.Context, request AmbiguityRequest) (AmbiguityResult, error) {
	return f(ctx, request)
}

// DisabledAmbiguityResolver is the production-safe default. Installing an AI
// client alone changes no matching behavior; callers must explicitly inject it.
type DisabledAmbiguityResolver struct{}

func (DisabledAmbiguityResolver) ResolveAmbiguity(context.Context, AmbiguityRequest) (AmbiguityResult, error) {
	return AmbiguityResult{SchemaVersion: AmbiguitySchemaVersion, Decision: AmbiguityAbstain}, nil
}

// GuardedAmbiguityResolver validates an explicitly enabled backend and converts
// low-confidence answers to ABSTAIN so deterministic matching remains in charge.
type GuardedAmbiguityResolver struct {
	Enabled       bool
	Backend       AmbiguityResolver
	MinConfidence float64
}

func (g GuardedAmbiguityResolver) ResolveAmbiguity(ctx context.Context, request AmbiguityRequest) (AmbiguityResult, error) {
	if !g.Enabled || g.Backend == nil {
		return DisabledAmbiguityResolver{}.ResolveAmbiguity(ctx, request)
	}
	result, err := g.Backend.ResolveAmbiguity(ctx, request)
	if err != nil {
		return AmbiguityResult{SchemaVersion: AmbiguitySchemaVersion, Decision: AmbiguityAbstain}, err
	}
	if err := ValidateAmbiguityResult(request, result); err != nil {
		return AmbiguityResult{SchemaVersion: AmbiguitySchemaVersion, Decision: AmbiguityAbstain}, err
	}
	minimum := g.MinConfidence
	if minimum <= 0 {
		minimum = 0.85
	}
	if result.Decision == AmbiguityMatch && result.Confidence < minimum {
		result.Decision = AmbiguityAbstain
		result.CandidateID = ""
		result.Evidence = append(result.Evidence, fmt.Sprintf("below_min_confidence:%.2f", minimum))
	}
	return result, nil
}

func ValidateAmbiguityResult(request AmbiguityRequest, result AmbiguityResult) error {
	if request.SchemaVersion != AmbiguitySchemaVersion || result.SchemaVersion != AmbiguitySchemaVersion {
		return errors.New("unsupported ambiguity schema version")
	}
	if len(request.Candidates) < 2 || len(request.Candidates) > 8 {
		return fmt.Errorf("ambiguity request must contain 2 to 8 candidates, got %d", len(request.Candidates))
	}
	known := make(map[string]struct{}, len(request.Candidates))
	for _, candidate := range request.Candidates {
		if strings.TrimSpace(candidate.CandidateID) == "" {
			return errors.New("candidate ID is required")
		}
		if _, duplicate := known[candidate.CandidateID]; duplicate {
			return fmt.Errorf("duplicate candidate ID %q", candidate.CandidateID)
		}
		known[candidate.CandidateID] = struct{}{}
	}
	if math.IsNaN(result.Confidence) || result.Confidence < 0 || result.Confidence > 1 {
		return fmt.Errorf("confidence must be between 0 and 1, got %v", result.Confidence)
	}
	switch result.Decision {
	case AmbiguityMatch:
		if _, ok := known[result.CandidateID]; !ok {
			return fmt.Errorf("AI selected unknown candidate ID %q", result.CandidateID)
		}
		if strings.TrimSpace(result.Model) == "" || strings.TrimSpace(result.ModelVersion) == "" {
			return errors.New("AI match must identify model and model version")
		}
	case AmbiguityNoMatch, AmbiguityAbstain:
		if result.CandidateID != "" {
			return errors.New("non-match decision must not select a candidate")
		}
	default:
		return fmt.Errorf("unknown ambiguity decision %q", result.Decision)
	}
	return nil
}
